// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PIMHotelaria.Data;

namespace PIMHotelaria.Migrations
{
    [DbContext(typeof(PIMHotelariaContext))]
    [Migration("20211101221516_AddConexãoLocal")]
    partial class AddConexãoLocal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PIMHotelaria.Pages.Clientes.Clientes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apelido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cpf")
                        .HasColumnType("int");

                    b.Property<string>("nome_Cliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("telefone")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("PIMHotelaria.Pages.Contas.Contas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("agencia")
                        .HasColumnType("int");

                    b.Property<int>("cvc")
                        .HasColumnType("int");

                    b.Property<int>("num_Cartão")
                        .HasColumnType("int");

                    b.Property<int>("num_Conta")
                        .HasColumnType("int");

                    b.Property<string>("titular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tp_Cartão")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("PIMHotelaria.Pages.Reservas.Reservas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dt_Entrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dt_Saida")
                        .HasColumnType("datetime2");

                    b.Property<bool>("mtd_Acesso")
                        .HasColumnType("bit");

                    b.Property<int>("num_Pessoas")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
